base_url = "https://annajarlbo.dk"
title = "Anna Jarlbo, fashion interpreter"
compile_sass = true

build_search_index = false


[markdown]

[extra]
favicon = "images/favicon_package_v0.16/favicon.ico"
author = ""
name = ""
header_links = []
